#!/bin/bash
#note* need to modify to handle different obs type numbering between DT2 and Cheyenne implementations of filter
#DOPPLER_RADIAL_VELOCITY is 164 on DT2, 36 on Cheyenne
#multimem #output mems currently fixed at 20. Need to modify to dynamically find #output mems
begin=`awk '$1=="first:"{begin_row=NR} END{print begin_row}' ${1}`
echo $begin
awk -v priorline="$priorline" -v postline="$postline" -v begin="$begin" 'BEGIN{OFS=",";temp=-888888}  NR==0{last=NA;increment=0} increment!=0{increment+=1} last=="OBS"{increment=1} increment==47{val_qc=$1} increment==6{priorA=$1} increment==7{postA=$1} increment==8{priorB=$1} increment==9{postB=$1} increment==10{priorC=$1} increment==11{postC=$1} increment==12{priorD=$1} increment==13{postD=$1} increment==14{priorE=$1} increment==15{postE=$1} increment==16{priorF=$1} increment==17{postF=$1} increment==18{priorG=$1} increment==19{postG=$1} increment==20{priorH=$1} increment==21{postH=$1} increment==22{priorI=$1} increment==23{postI=$1} increment==24{priorJ=$1} increment==25{postJ=$1} increment==26{priorK=$1} increment==27{postK=$1} increment==28{priorL=$1} increment==29{postL=$1} increment==30{priorM=$1} increment==31{postM=$1} increment==32{priorN=$1} increment==33{postN=$1} increment==34{priorO=$1} increment==35{postO=$1} increment==36{priorP=$1} increment==37{postP=$1} increment==38{priorQ=$1} increment==39{postQ=$1} increment==40{priorR=$1} increment==41{postR=$1} increment==42{priorS=$1} increment==43{postS=$1} increment==44{priorT=$1} increment==45{postT=$1} increment==4{prior_sp=$1} increment==5{post_sp=$1} increment==53{type=$1} increment==1{value=$1} increment==51{x_loc=$1; y_loc=$2;z_loc=$3} {if(increment==55 && (type!="36" && type !="164")){obs_err=$1;print type,value,x_loc,y_loc,z_loc,val_qc,ob_num,priorA,priorB,priorC,priorD,priorE,priorF,priorG,priorH,priorI,priorJ,priorK,priorL,priorM,priorN,priorO,priorP,priorQ,priorR,priorS,priorT,postA,postB,postC,postD,postE,postF,postG,postH,postI,postJ,postK,postL,postM,postN,postO,postP,postQ,postR,postS,postT,prior_sp,post_sp,obs_err}} {if(increment==62 && (type=="36" || type=="164")){obs_err=$1;print type,value,x_loc,y_loc,z_loc,val_qc,ob_num,priorA,priorB,priorC,priorD,priorE,priorF,priorG,priorH,priorI,priorJ,priorK,priorL,priorM,priorN,priorO,priorP,priorQ,priorR,priorS,priorT,postA,postB,postC,postD,postE,postF,postG,postH,postI,postJ,postK,postL,postM,postN,postO,postP,postQ,postR,postS,postT,prior_sp,post_sp,obs_err}} NR>begin{last=$1} last=="OBS"{ob_num=$2}' ${1} > ${2}


#last=="kind"{flag=3}
